[[headers]]
	for = "/*"
	[headers.values]
		X-Content-Type-Options = "nosniff"
		X-DNS-Prefetch-Control = "on"
		X-Frame-Options = "DENY"
		X-XSS-Protection = "1; mode=block"

		Referrer-Policy = "same-origin"
		Permissions-Policy = "camera=(), microphone=(), geolocation=(), interest-cohort=()"
		Content-Security-Policy = "default-src 'none'; script-src 'self'; style-src 'self' 'unsafe-inline' fonts.googleapis.com; img-src 'self' blob: data: www.datocms-assets.com images.unsplash.com; font-src 'self' fonts.gstatic.com data:; connect-src 'self'; prefetch-src 'self';"