// Libraries
import Head from 'next/head';
import { H, Section } from 'react-headings';

// Imports
import { CaseGrid, HomeHero } from '../components/content';
import { gql } from '@apollo/client';
import client from '../apollo-client';

// GraphQL
export async function getStaticProps() {
    const { data } = await client.query({
        query: gql`
            query HomePage {
                home {
                    id
                    heroContent {
                        value
                    }
                    heroImage {
                        url
                        alt
                        height
                        width
                        blurUpThumb
                    }
                    casesHeading
                }
                allCases(orderBy: year_DESC) {
                    client
                    slug
                    year
                    excerpt {
                        value
                    }
                    thumbnail {
                        url
                        alt
                        height
                        width
                        blurUpThumb
                    }
                    logo {
                        url
                        alt
                        height
                        width
                    }
                }
            }
        `,
    });

    return {
        props: { data },
    };
}

// Components
const Home = ({ data }) => {
    return (
        <Section>
            <Head>
                <title>LabelNoir</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <HomeHero content={data.home.heroContent} image={data.home.heroImage} />

            <CaseGrid projects={data.allCases}>
                <H>{data.home.casesHeading}</H>
            </CaseGrid>
        </Section>
    );
};

// Exports
export default Home;
